name: Actions Workflow

on: [push, pull_request]
env: 
  DAY_OF_WEEK: Monday
  SUPER_SECRET: ${{secrets.MY_SECRET}}

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   env:
     Greeting: Hello
   steps:
    - name: "Say Hello Caio, itś Monday"
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK and you cant see this supersecret ${{env.SUPER_SECRET}}" "${GITHUB_REPOSITORY}"
      env:
        First_Name: Caio
    - name: checkout 
      uses: actions/checkout@v2.4.2
    - name: List File
      run: |
        pwd
        ls -a 
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
       who-to-greet: Caio Queiroz
    - name: Log Greeting time
      run: echo "${{steps.greet.outputs.time}}"
