name: Actions Workflow

on: push
env: 
  DAY_OF_WEEK: Monday

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   env:
     Greeting: Hello
   steps:
    - name: "Say Hello Caio, itś Monday"
      run: echo "$Greeting $FirstName. Today is $DAY_OF_WEEK"
      env:
        First_Name: Caio
    - name: checkout 
      uses: actions/checkout@v2.4.2
    - name: List File
      run: |
        pwd
        ls -a 
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
       who-to-greet: Caio Queiroz
    - name: Log Greeting time
      run: echo "${{steps.greet.outputs.time}}"
