name: Actions Workflow

on: push

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   steps:
    - name: checkout 
      uses: actions/checkout@v2.4.2
    - name: List File
      run: |
        pwd
        ls -a 
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
       who-to-greet: Caio Queiroz
    - name: Log Greeting time
      run: echo "${{steps.greet.outputs.time}}"
