name: Actions Workflow

on: 
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"
  # push:
  pull_request:
    types: [closed, assigned, opened, reopened ]
      
     
env: 
  DAY_OF_WEEK: Sunday
  SUPER_SECRET: ${{secrets.MY_SECRET}}

jobs:
  run-github-actions:
   runs-on: ubuntu-latest
   env:
     Greeting: Hello
   steps:
    - name: "Say Hello Caio, itś Sunday"
      run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK and you cant see this supersecret ${{env.SUPER_SECRET}}" "${GITHUB_REPOSITORY}"
      env:
        First_Name: Caio
    - name: checkout 
      uses: actions/checkout@v2.4.2
    - name: List File
      run: |
        pwd
        ls -a 
    - name: Simple JS Actions
      id: greet
      uses: actions/hello-world-javascript-action@v1
      with:
       who-to-greet: Caio Queirozi
    - name: Log Greeting time
      run: echo "${{steps.greet.outputs.time}}"
